name: Publish to Dockerhub

on:
  push:
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        
#      - name: Set environment variable
#        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lura:latest
          
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: DanNguyen8189/helm-test
          event-type: my-event
          client-payload: '{"testing!!": "testing"}'
