name: Publish to Dockerhub (test)

on:
  push:
    branches:
      - 'main'
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        
      - name: Automated Version Bump                  # This action step reads and updates the version number acc to commit message
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output Step                             # Optional: Prints the new version
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lura:latest, ${{ secrets.DOCKERHUB_USERNAME }}/lura:${{ steps.version-bump.outputs.newTag }}
